/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as masterSol from "./Master.sol";
export type { masterSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { Lock } from "./Lock";
export type { VerifySignature } from "./VerifySignature";
